CREATE TABLE EVENTO(
    COD_EVENTO NUMBER(3)PRIMARY kEY,
    TIPO_EVENTO VARCHAR2(20) CHECK(TIPO_EVENTO IN ('CONFERENCIA', 'TALLERES', 'ACTIVIDADES')) UNIQUE,
    NOMBRE VARCHAR2(50),
    FECHA DATE,
    HORA TIME,
    DURACION NUMBER(3),
    LUGAR VARCHAR2(50)
);
CREATE TABLE USUARIO(
    COD_USUARIO NUMBER(5)PRIMARY KEY,
    NOMBRE VARCHAR2(20),
    CORREO VARCHAR2(50),
    CONTRASEÑA VARCHAR2(30)
);
CREATE TABLE ORGANIZADOR(
    COD_EMPLE NUMBER(3)PRIMARY KEY,
    TELEFONO NUMBER(9),
    CORREO VARCHAR2(50),
    FOREIGN KEY (COD_EVENTO) REFERENCES EVENTOS (COD_EVENTO)
);
